CREATE TABLE channel
(
    channel_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    name       VARCHAR(255),
    CONSTRAINT pk_channel PRIMARY KEY (channel_id)
);

CREATE TABLE follow_channel
(
    follow_channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_id        UUID,
    member_id         BIGINT,
    CONSTRAINT pk_follow_channel PRIMARY KEY (follow_channel_id)
);

CREATE TABLE location_message
(
    location_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    updated_at          TIMESTAMP WITH TIME ZONE,
    position            GEOMETRY(Point, 4326),
    channel_id          UUID,
    member_id           BIGINT,
    CONSTRAINT pk_location_message PRIMARY KEY (location_message_id)
);

CREATE TABLE member
(
    member_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50),
    is_enabled BOOLEAN,
    mobile     VARCHAR(255),
    password   VARCHAR(100),
    role       INTEGER,
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);

CREATE TABLE message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    message    VARCHAR(255),
    channel_id UUID,
    member_id  BIGINT,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE member
    ADD CONSTRAINT uc_member_mobile UNIQUE (mobile);

ALTER TABLE follow_channel
    ADD CONSTRAINT FK_FOLLOW_CHANNEL_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channel (channel_id);

ALTER TABLE follow_channel
    ADD CONSTRAINT FK_FOLLOW_CHANNEL_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE location_message
    ADD CONSTRAINT FK_LOCATION_MESSAGE_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channel (channel_id);

ALTER TABLE location_message
    ADD CONSTRAINT FK_LOCATION_MESSAGE_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channel (channel_id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);
