spring:
  profiles:
    group:
      local: "local"
      prod: "prod"
      test: "test"

logging:
  level:
    root: INFO
    com.where.server: DEBUG
    org.springframework.web: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %logger{36} - %msg%n"

